# Tłumaczenia PL dla DevExpress.ExpressApp (wszystkie Blazor-relevant subpackages, v26.1)
# Wywołanie: .\expressApp-pl.ps1 -SrcRoot <ścieżka do src\DevExpress.ExpressApp>
param([Parameter(Mandatory)][string]$SrcRoot)

function Patch-Resx([string]$PlResx, [hashtable]$Trans, [string]$Label) {
    if (-not (Test-Path $PlResx)) { Write-Warning "Brak: $PlResx"; return }
    [xml]$xml = Get-Content $PlResx -Encoding UTF8
    $added = 0; $skipped = 0
    foreach ($key in $Trans.Keys) {
        if ($xml.root.data | Where-Object { $_.name -eq $key }) { $skipped++; continue }
        $node = $xml.CreateElement("data"); $node.SetAttribute("name", $key); $node.SetAttribute("xml:space", "preserve")
        $val = $xml.CreateElement("value"); $val.InnerText = $Trans[$key]
        $null = $node.AppendChild($val); $null = $xml.root.AppendChild($node); $added++
    }
    Write-Host "$Label PL: dodano=$added pominięto=$skipped"
    $s = [System.Xml.XmlWriterSettings]::new()
    $s.Encoding = [System.Text.UTF8Encoding]::new($true); $s.Indent = $true; $s.NewLineChars = "`r`n"
    $xw = [System.Xml.XmlWriter]::Create($PlResx, $s); $xml.Save($xw); $xw.Close()
}

# ── DevExpress.ExpressApp (core) ───────────────────────────────────────────────
Patch-Resx "$SrcRoot\DevExpress.ExpressApp\ModuleLocalizationResources.pl.resx" -Label "ExpressApp.Core" ([ordered]@{
    "Non-calculated\BOModel\DevExpress.ExpressApp.SystemModule.DashboardViewItemDescriptor\Caption"                          = "Deskryptor elementu dashboardu"
    "Non-calculated\BOModel\DevExpress.ExpressApp.SystemModule.ModelDifferenceCopyParameters\Caption"                       = "Kopiuj różnice modelu"
    "Non-calculated\BOModel\DevExpress.ExpressApp.SystemModule.ModelDifferenceCopyParameters\OwnMembers\CopyBehavior\Caption" = "Zachowanie kopiowania"
    "Non-calculated\BOModel\DevExpress.ExpressApp.SystemModule.ModelDifferenceCopyParameters\OwnMembers\SourceModelDifference\Caption" = "Źródłowa różnica modelu"
    "Non-calculated\BOModel\DevExpress.ExpressApp.SystemModule.ModelDifferenceCopyParameters\OwnMembers\TargetModelDifferences\Caption" = "Docelowe różnice modelu"
    "Non-calculated\BOModel\DevExpress.ExpressApp.SystemModule.Notifications.PostponeTime\Caption"                           = "Czas odroczenia"
    "Non-calculated\BOModel\DevExpress.ExpressApp.SystemModule.StaticImageDashboardOrganizationItem\OwnMembers\SvgImageWidth\Caption"  = "Szerokość obrazu SVG"
    "Non-calculated\BOModel\DevExpress.ExpressApp.SystemModule.StaticImageDashboardOrganizationItem\OwnMembers\SvgImageHeight\Caption" = "Wysokość obrazu SVG"
    "Non-calculated\Localization\Captions\DiagnosticChildWindowAddition\Value"                                               = "(Okno podrzędne)"
    "Non-calculated\Localization\Captions\ListView\Value"                                                                    = "Lista"
    "Non-calculated\Localization\Captions\LogInWithActionCaption\Value"                                                      = "Zaloguj się przez"
    "Non-calculated\Localization\DashboardOrganizationItems\ActionContainer\Value"                                           = "Kontener akcji"
    "Non-calculated\Localization\Enums\DevExpress.ExpressApp.ModelDifferenceCopyBehavior\Value"                              = "Zachowanie kopiowania różnicy modelu"
    "Non-calculated\Localization\Enums\DevExpress.ExpressApp.ModelDifferenceCopyBehavior\Overwrite\Value"                    = "Nadpisz"
    "Non-calculated\Localization\Messages\TagBoxListCannotEditWarning\Value"                                                  = "Musisz najpierw zapisać tagi, aby móc je edytować."
    # System.Drawing.KnownColor — nazwy kolorów PL
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Value"                    = "Znany kolor"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\ActiveBorder\Value"       = "Aktywna ramka"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\ActiveCaption\Value"      = "Aktywny pasek tytułu"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\ActiveCaptionText\Value"  = "Tekst aktywnego paska tytułu"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\AliceBlue\Value"          = "Błękit Alice"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\AntiqueWhite\Value"       = "Antyczna biel"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\AppWorkspace\Value"       = "Obszar roboczy aplikacji"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Aqua\Value"               = "Aqua"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Aquamarine\Value"         = "Akwamaryna"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Azure\Value"              = "Lazur"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Beige\Value"              = "Beżowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Bisque\Value"             = "Biszkopt"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Black\Value"              = "Czarny"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\BlanchedAlmond\Value"     = "Blanszowany migdał"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Blue\Value"               = "Niebieski"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\BlueViolet\Value"         = "Niebieskofioletowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Brown\Value"              = "Brązowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\BurlyWood\Value"          = "Drzewo jesionowe"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\ButtonFace\Value"         = "Powierzchnia przycisku"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\ButtonHighlight\Value"    = "Podświetlenie przycisku"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\ButtonShadow\Value"       = "Cień przycisku"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\CadetBlue\Value"          = "Niebieski kadet"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Chartreuse\Value"         = "Chartreuse"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Chocolate\Value"          = "Czekoladowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Control\Value"            = "Kontrolka"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\ControlDark\Value"        = "Ciemna kontrolka"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\ControlDarkDark\Value"    = "Bardzo ciemna kontrolka"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\ControlLight\Value"       = "Jasna kontrolka"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\ControlLightLight\Value"  = "Bardzo jasna kontrolka"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\ControlText\Value"        = "Tekst kontrolki"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Coral\Value"              = "Koral"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\CornflowerBlue\Value"     = "Chabry"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Cornsilk\Value"           = "Jedwab kukurydziany"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Crimson\Value"            = "Karmazyn"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Cyan\Value"               = "Cyjan"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkBlue\Value"           = "Ciemny niebieski"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkCyan\Value"           = "Ciemny cyjan"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkGoldenrod\Value"      = "Ciemny złotnik"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkGray\Value"           = "Ciemny szary"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkGreen\Value"          = "Ciemny zielony"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkKhaki\Value"          = "Ciemne khaki"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkMagenta\Value"        = "Ciemna magenta"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkOliveGreen\Value"     = "Ciemna oliwkowa zieleń"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkOrange\Value"         = "Ciemny pomarańczowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkOrchid\Value"         = "Ciemna orchidea"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkRed\Value"            = "Ciemny czerwony"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkSalmon\Value"         = "Ciemny łosoś"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkSeaGreen\Value"       = "Ciemna morska zieleń"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkSlateBlue\Value"      = "Ciemny łupkowy niebieski"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkSlateGray\Value"      = "Ciemny łupkowy szary"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkTurquoise\Value"      = "Ciemny turkus"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DarkViolet\Value"         = "Ciemny fiolet"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DeepPink\Value"           = "Głęboki róż"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DeepSkyBlue\Value"        = "Głęboki błękit nieba"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Desktop\Value"            = "Pulpit"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DimGray\Value"            = "Przyciemniony szary"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\DodgerBlue\Value"         = "Niebieski Dodger"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Firebrick\Value"          = "Cegła ognista"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\FloralWhite\Value"        = "Kwiatowa biel"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\ForestGreen\Value"        = "Leśna zieleń"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Fuchsia\Value"            = "Fuksja"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Gainsboro\Value"          = "Gainsboro"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\GhostWhite\Value"         = "Upiorna biel"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Gold\Value"               = "Złoty"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Goldenrod\Value"          = "Złotnik"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\GradientActiveCaption\Value"  = "Gradient aktywnego paska tytułu"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\GradientInactiveCaption\Value" = "Gradient nieaktywnego paska tytułu"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Gray\Value"               = "Szary"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\GrayText\Value"           = "Szary tekst"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Green\Value"              = "Zielony"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\GreenYellow\Value"        = "Zielonożółty"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Highlight\Value"          = "Zaznaczenie"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\HighlightText\Value"      = "Tekst zaznaczenia"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Honeydew\Value"           = "Spadź"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\HotPink\Value"            = "Gorący róż"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\HotTrack\Value"           = "Aktywny ślad"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\InactiveBorder\Value"     = "Nieaktywna ramka"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\InactiveCaption\Value"    = "Nieaktywny pasek tytułu"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\InactiveCaptionText\Value" = "Tekst nieaktywnego paska tytułu"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\IndianRed\Value"          = "Indyjski czerwony"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Indigo\Value"             = "Indygo"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Info\Value"               = "Dymek"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\InfoText\Value"           = "Tekst dymka"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Ivory\Value"              = "Kość słoniowa"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Khaki\Value"              = "Khaki"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Lavender\Value"           = "Lawenda"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LavenderBlush\Value"      = "Blady lawendowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LawnGreen\Value"          = "Trawiasty"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LemonChiffon\Value"       = "Cytrynowy szyfon"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LightBlue\Value"          = "Jasny niebieski"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LightCoral\Value"         = "Jasny koral"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LightCyan\Value"          = "Jasny cyjan"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LightGoldenrodYellow\Value" = "Jasny żółtawozłoty"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LightGray\Value"          = "Jasny szary"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LightGreen\Value"         = "Jasny zielony"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LightPink\Value"          = "Jasny róż"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LightSalmon\Value"        = "Jasny łosoś"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LightSeaGreen\Value"      = "Jasna morska zieleń"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LightSkyBlue\Value"       = "Jasny błękit nieba"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LightSlateGray\Value"     = "Jasny łupkowy szary"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LightSteelBlue\Value"     = "Jasny stalowy niebieski"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LightYellow\Value"        = "Jasny żółty"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Lime\Value"               = "Limonkowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\LimeGreen\Value"          = "Limonkowa zieleń"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Linen\Value"              = "Lniany"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Magenta\Value"            = "Magenta"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Maroon\Value"             = "Kasztanowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\MediumAquamarine\Value"   = "Średnia akwamaryna"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\MediumBlue\Value"         = "Średni niebieski"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\MediumOrchid\Value"       = "Średnia orchidea"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\MediumPurple\Value"       = "Średni fiolet"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\MediumSeaGreen\Value"     = "Średnia morska zieleń"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\MediumSlateBlue\Value"    = "Średni łupkowy niebieski"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\MediumSpringGreen\Value"  = "Średnia wiosenna zieleń"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\MediumTurquoise\Value"    = "Średni turkus"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\MediumVioletRed\Value"    = "Średnia fioletowa czerwień"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Menu\Value"               = "Menu"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\MenuBar\Value"            = "Pasek menu"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\MenuHighlight\Value"      = "Podświetlenie menu"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\MenuText\Value"           = "Tekst menu"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\MidnightBlue\Value"       = "Niebieski północy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\MintCream\Value"          = "Miętowy krem"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\MistyRose\Value"          = "Mglista róża"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Moccasin\Value"           = "Mokasyn"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\NavajoWhite\Value"        = "Biały Navajo"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Navy\Value"               = "Granatowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\OldLace\Value"            = "Stara koronka"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Olive\Value"              = "Oliwkowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\OliveDrab\Value"          = "Ciemna oliwka"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Orange\Value"             = "Pomarańczowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\OrangeRed\Value"          = "Pomarańczowoczerwony"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Orchid\Value"             = "Orchidea"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\PaleGoldenrod\Value"      = "Blady złotnik"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\PaleGreen\Value"          = "Blada zieleń"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\PaleTurquoise\Value"      = "Blady turkus"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\PaleVioletRed\Value"      = "Blada fioletowoczerwień"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\PapayaWhip\Value"         = "Bita śmietana papai"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\PeachPuff\Value"          = "Brzoskwiniowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Peru\Value"               = "Peru"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Pink\Value"               = "Różowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Plum\Value"               = "Śliwkowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\PowderBlue\Value"         = "Pudrowy niebieski"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Purple\Value"             = "Fioletowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\RebeccaPurple\Value"      = "Fiolet Rebecki"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Red\Value"                = "Czerwony"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\RosyBrown\Value"          = "Różowobrązowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\RoyalBlue\Value"          = "Królewski niebieski"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\SaddleBrown\Value"        = "Brąz siodła"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Salmon\Value"             = "Łososiowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\SandyBrown\Value"         = "Piaskowożółty"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\ScrollBar\Value"          = "Pasek przewijania"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\SeaGreen\Value"           = "Morska zieleń"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\SeaShell\Value"           = "Muszla morska"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Sienna\Value"             = "Sjenna"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Silver\Value"             = "Srebrny"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\SkyBlue\Value"            = "Błękit nieba"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\SlateBlue\Value"          = "Łupkowy niebieski"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\SlateGray\Value"          = "Łupkowy szary"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Snow\Value"               = "Śnieg"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\SpringGreen\Value"        = "Wiosenna zieleń"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\SteelBlue\Value"          = "Stalowy niebieski"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Tan\Value"                = "Tan"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Teal\Value"               = "Morski"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Thistle\Value"            = "Oset"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Tomato\Value"             = "Pomidorowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Transparent\Value"        = "Przezroczysty"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Turquoise\Value"          = "Turkusowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Violet\Value"             = "Fioletowy"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Wheat\Value"              = "Pszeniczny"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\White\Value"              = "Biały"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\WhiteSmoke\Value"         = "Biały dym"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Window\Value"             = "Okno"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\WindowFrame\Value"        = "Ramka okna"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\WindowText\Value"         = "Tekst okna"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\Yellow\Value"             = "Żółty"
    "Non-calculated\Localization\Enums\System.Drawing.KnownColor\YellowGreen\Value"        = "Żółtozielony"
    # Dashboard views
    "Views\DashboardCreationInfo_DetailView\Caption"                                        = "Kreator dashboardu"
    "Views\DashboardCreationInfo_DetailView\Items\NavigationGroupName\Caption"              = "Docelowa grupa nawigacji"
    "Views\DashboardCreationInfo_ListView\Caption"                                          = "Kreator dashboardu"
    "Views\DashboardCreationInfo_ListView\Columns\NavigationGroupName\Caption"             = "Docelowa grupa nawigacji"
    "Views\DashboardCreationInfo_LookupListView\Caption"                                   = "Kreator dashboardu"
    "Views\DashboardCreationInfo_ViewItems_ListView\Caption"                               = "Element organizacji dashboardu"
    "Views\DashboardOrganizationItem_DetailView\Caption"                                   = "Element organizacji dashboardu"
    "Views\DashboardOrganizationItem_ListView\Caption"                                     = "Element organizacji dashboardu"
    "Views\DashboardOrganizationItem_LookupListView\Caption"                               = "Element organizacji dashboardu"
    "Views\DashboardOrganizer_DetailView\Caption"                                          = "Organizator dashboardu"
    "Views\DashboardOrganizer_DetailView\Items\ViewItems\Caption"                          = "Elementy widoku"
    "Views\DashboardOrganizer_ListView\Caption"                                            = "Organizator dashboardu"
    "Views\DashboardOrganizer_LookupListView\Caption"                                      = "Organizator dashboardu"
    "Views\DashboardOrganizer_ViewItems_ListView\Caption"                                  = "Element organizacji dashboardu"
    "Views\DashboardViewItemDescriptor_DetailView\Caption"                                 = "Deskryptor elementu dashboardu"
    "Views\DashboardViewItemDescriptor_ListView\Caption"                                   = "Deskryptor elementu dashboardu"
    "Views\DashboardViewItemDescriptor_ListView\Columns\ViewId\Caption"                    = "ID widoku"
    "Views\DashboardViewItemDescriptor_ListView\Columns\ViewDescription\Caption"           = "Opis widoku"
    "Views\DashboardViewItemDescriptor_LookupListView\Caption"                             = "Deskryptor elementu dashboardu"
    "Views\DashboardViewItemDescriptor_LookupListView\Columns\ViewDescription\Caption"     = "Opis widoku"
    "Views\ModelDifferenceCopyParameters_DetailView\Caption"                               = "Kopiuj różnice modelu"
    "Views\ModelDifferenceCopyParameters_DetailView\CaptionColon"                          = ":"
    "Views\ModelDifferenceCopyParameters_DetailView\Items\CopyBehavior\Caption"            = "Zachowanie kopiowania"
    "Views\ModelDifferenceCopyParameters_DetailView\Items\SourceModelDifference\Caption"   = "Źródłowa różnica modelu"
    "Views\ModelDifferenceCopyParameters_DetailView\Items\TargetModelDifferences\Caption"  = "Docelowe różnice modelu"
    "Views\ModelDifferenceCopyParameters_ListView\Caption"                                 = "Kopiuj różnice modelu"
    "Views\ModelDifferenceCopyParameters_ListView\Columns\CopyBehavior\Caption"            = "Zachowanie kopiowania"
    "Views\ModelDifferenceCopyParameters_ListView\Columns\SourceModelDifference\Caption"   = "Źródłowa różnica modelu"
    "Views\ModelDifferenceCopyParameters_LookupListView\Caption"                           = "Kopiuj różnice modelu"
    "Views\ModelDifferenceCopyParameters_LookupListView\Columns\CopyBehavior\Caption"      = "Zachowanie kopiowania"
    "Views\ModelDifferenceCopyParameters_LookupListView\Columns\SourceModelDifference\Caption" = "Źródłowa różnica modelu"
    "Views\PostponeTime_DetailView\Caption"                                                = "Czas odroczenia"
    "Views\PostponeTime_DetailView\CaptionColon"                                           = ":"
    "Views\PostponeTime_DetailView\Items\ID\Caption"                                       = "ID"
    "Views\PostponeTime_ListView\Caption"                                                  = "Czas odroczenia"
    "Views\PostponeTime_ListView\Columns\ID\Caption"                                       = "ID"
    "Views\PostponeTime_LookupListView\Caption"                                            = "Czas odroczenia"
    "Views\ProcessDataLockingInfoCustomMergeDialog_DetailView\Caption"                     = "Ostrzeżenie"
    "Views\ProcessDataLockingInfoCustomMergeDialog_DetailView\CaptionColon"                = ":"
    "Views\ProcessDataLockingInfoMergeDialog_DetailView\CaptionColon"                      = ":"
    "Views\ProcessDataLockingInfoRefreshDialog_DetailView\CaptionColon"                    = ":"
    "Views\StaticImageDashboardOrganizationItem_DetailView\Caption"                        = "Statyczny obraz"
    "Views\StaticImageDashboardOrganizationItem_DetailView\CaptionColon"                   = ":"
    "Views\StaticImageDashboardOrganizationItem_DetailView\Items\ImageName\Caption"        = "Nazwa obrazu"
    "Views\StaticImageDashboardOrganizationItem_DetailView\Items\SvgImageHeight\Caption"   = "Wysokość obrazu SVG"
    "Views\StaticImageDashboardOrganizationItem_DetailView\Items\SvgImageWidth\Caption"    = "Szerokość obrazu SVG"
    "Views\StaticImageDashboardOrganizationItem_ListView\Caption"                          = "Statyczny obraz"
    "Views\StaticImageDashboardOrganizationItem_ListView\Columns\ImageName\Caption"        = "Nazwa obrazu"
    "Views\StaticImageDashboardOrganizationItem_ListView\Columns\SvgImageWidth\Caption"    = "Szerokość SVG"
    "Views\StaticImageDashboardOrganizationItem_ListView\Columns\SvgImageHeight\Caption"   = "Wysokość SVG"
    "Views\StaticImageDashboardOrganizationItem_LookupListView\Caption"                    = "Statyczny obraz"
    "Views\StaticImageDashboardOrganizationItem_LookupListView\Columns\ImageName\Caption"  = "Nazwa obrazu"
    "Views\StaticTextDashboardOrganizationItem_DetailView\Caption"                         = "Statyczny tekst"
    "Views\StaticTextDashboardOrganizationItem_DetailView\CaptionColon"                    = ":"
    "Views\StaticTextDashboardOrganizationItem_ListView\Caption"                           = "Statyczny tekst"
    "Views\StaticTextDashboardOrganizationItem_LookupListView\Caption"                     = "Statyczny tekst"
    "Views\ViewDashboardOrganizationItem_DetailView\CaptionColon"                          = ":"
    "Views\ViewDashboardOrganizationItem_DetailView\Items\ObjectType\Caption"              = "Typ obiektu"
    "Views\ViewDashboardOrganizationItem_ListView\Columns\ObjectType\Caption"              = "Typ obiektu"
    "Views\ViewDashboardOrganizationItem_LookupListView\Columns\ObjectType\Caption"        = "Typ obiektu"
})

# ── DevExpress.ExpressApp.Blazor ───────────────────────────────────────────────
Patch-Resx "$SrcRoot\DevExpress.ExpressApp.Blazor\ModuleLocalizationResources.pl.resx" -Label "ExpressApp.Blazor" ([ordered]@{
    "Non-calculated\ActionDesign\ActionToRibbonMapping\Home\ObjectsCreation\Caption"            = "Tworzenie rekordów"
    "Non-calculated\ActionDesign\ActionToRibbonMapping\Home\RecordsNavigation\Caption"          = "Nawigacja po rekordach"
    "Non-calculated\ActionDesign\ActionToRibbonMapping\Tools\Diagnostic\Caption"                = "Diagnostyka"
    "Non-calculated\ActionDesign\ActionToRibbonMapping\Misc\Caption"                            = "Różne"
    "Non-calculated\ActionDesign\ActionToRibbonMapping\Misc\Unspecified\Caption"                = "Nieokreślone"
    "Non-calculated\Localization\VisualComponents\LayoutEditor\PivotGridContextMenu\ClearFilter\Value"          = "Wyczyść filtr"
    "Non-calculated\Localization\VisualComponents\LayoutEditor\PivotGridContextMenu\CollapseAllColumns\Value"   = "Zwiń wszystkie kolumny"
    "Non-calculated\Localization\VisualComponents\LayoutEditor\PivotGridContextMenu\CollapseAllGroups\Value"    = "Zwiń wszystkie grupy"
    "Non-calculated\Localization\VisualComponents\LayoutEditor\PivotGridContextMenu\CollapseAllRows\Value"      = "Zwiń wszystkie wiersze"
    "Non-calculated\Localization\VisualComponents\LayoutEditor\PivotGridContextMenu\ExpandAllColumns\Value"     = "Rozwiń wszystkie kolumny"
    "Non-calculated\Localization\VisualComponents\LayoutEditor\PivotGridContextMenu\ExpandAllGroups\Value"      = "Rozwiń wszystkie grupy"
    "Non-calculated\Localization\VisualComponents\LayoutEditor\PivotGridContextMenu\ExpandAllRows\Value"        = "Rozwiń wszystkie wiersze"
    "Non-calculated\Localization\VisualComponents\LayoutEditor\PivotGridContextMenu\ReloadData\Value"           = "Odśwież dane"
    "Non-calculated\Localization\VisualComponents\LayoutEditor\PivotGridContextMenu\ShowFieldList\Value"        = "Pokaż listę pól"
    "Non-calculated\Localization\VisualComponents\ThemeSwitcher\CustomColor\Value"              = "Kolor niestandardowy"
    "Non-calculated\Localization\VisualComponents\ThemeSwitcher\Dark\Value"                     = "Ciemny"
    "Non-calculated\Localization\VisualComponents\ThemeSwitcher\Light\Value"                    = "Jasny"
    "Non-calculated\Localization\VisualComponents\ThemeSwitcher\PresetColors\Value"             = "Kolory motywu"
})

# ── DevExpress.ExpressApp.Security ────────────────────────────────────────────
Patch-Resx "$SrcRoot\DevExpress.ExpressApp.Security\ModuleLocalizationResources.pl.resx" -Label "ExpressApp.Security" ([ordered]@{
    "Non-calculated\Localization\Enums\DevExpress.ExpressApp.Security.SecurityRequestOperations\Value" = "Operacje żądań bezpieczeństwa"
    "NavigationItems\Items\Default\Items\PermissionPolicyUser_ListView\Caption"                = "Użytkownicy"
    "Views\AuthenticationStandardLogonParameters_ListView\Caption"                             = "Parametry logowania standardowego"
    "Views\AuthenticationStandardLogonParameters_LookupListView\Caption"                       = "Parametry logowania standardowego"
    "Views\ChangePasswordOnLogonParameters_ListView\Caption"                                   = "Zmiana hasła przy logowaniu"
    "Views\ChangePasswordOnLogonParameters_LookupListView\Caption"                             = "Zmiana hasła przy logowaniu"
    "Views\ChangePasswordParameters_ListView\Caption"                                          = "Parametry zmiany hasła"
    "Views\ChangePasswordParameters_LookupListView\Caption"                                    = "Parametry zmiany hasła"
    "Views\PermissionPolicyMemberPermissionsObject_DetailView\Items\Members\NullText"          = "Wybierz członków"
    "Views\PermissionPolicyMemberPermissionsObject_ListView\Columns\Members\NullText"          = "Wybierz członków"
    "Views\PermissionPolicyMemberPermissionsObject_LookupListView\Columns\Members\NullText"    = "Wybierz członków"
    "Views\ResetPasswordParameters_Blazor_DetailView\Caption"                                  = "Resetuj hasło"
    "Views\ResetPasswordParameters_Blazor_DetailView\CaptionColon"                             = ":"
    "Views\ResetPasswordParameters_Blazor_DetailView\Items\Password\Caption"                   = "Hasło"
    "Views\ResetPasswordParameters_DetailView\CaptionColon"                                    = ":"
    "Views\ResetPasswordParameters_DetailView\Items\Password\Caption"                          = "Hasło"
    "Views\ResetPasswordParameters_ListView\Caption"                                           = "Parametry resetowania hasła"
    "Views\ResetPasswordParameters_ListView\Columns\Password\Caption"                          = "Hasło"
    "Views\ResetPasswordParameters_LookupListView\Caption"                                     = "Parametry resetowania hasła"
    "Views\ResetPasswordParameters_LookupListView\Columns\Password\Caption"                    = "Hasło"
    "Views\SecuredActionDescriptor_LookupListView\Columns\Category\Caption"                    = "Kategoria"
    "Views\SecuredActionDescriptor_LookupListView\Columns\Image\Caption"                       = "Obraz"
})

# ── DevExpress.ExpressApp.Notifications ───────────────────────────────────────
Patch-Resx "$SrcRoot\DevExpress.ExpressApp.Notifications\ModuleLocalizationResources.pl.resx" -Label "ExpressApp.Notifications" ([ordered]@{
    "Non-calculated\Localization\Enums\DevExpress.ExpressApp.Notifications.NotificationItemState\Value" = "Stan elementu powiadomienia"
    "Non-calculated\Localization\Enums\DevExpress.ExpressApp.Notifications.NotificationsType\Value"     = "Typ powiadomień"
    "Views\NotificationsObject_DetailView\Items\NotificationsState\Caption"                             = "Stan powiadomień"
    "Views\NotificationsObject_DetailView\Items\ShowNotificationsWindow\Caption"                        = "Pokaż okno powiadomień"
    "Views\NotificationsObject_ListView\Caption"                                                        = "Powiadomienia"
    "Views\NotificationsObject_ListView\Columns\NotificationsState\Caption"                             = "Stan"
    "Views\NotificationsObject_ListView\Columns\Postpone\Caption"                                       = "Odrocz"
    "Views\NotificationsObject_ListView\Columns\ShowNotificationsWindow\Caption"                        = "Pokaż okno"
    "Views\NotificationsObject_LookupListView\Caption"                                                  = "Powiadomienia"
    "Views\NotificationsObject_LookupListView\Columns\NotificationsState\Caption"                       = "Stan"
    "Views\NotificationsObject_LookupListView\Columns\Postpone\Caption"                                 = "Odrocz"
    "Views\NotificationsObject_LookupListView\Columns\ShowNotificationsWindow\Caption"                  = "Pokaż okno"
})

# ── DevExpress.ExpressApp.AI ───────────────────────────────────────────────────
Patch-Resx "$SrcRoot\DevExpress.ExpressApp.AI\ModuleLocalizationResources.pl.resx" -Label "ExpressApp.AI" ([ordered]@{
    "Non-calculated\BOModel\DevExpress.ExpressApp.AI.SmartPastePrompt\Caption"                 = "Prompt inteligentnego wklejania"
    "Non-calculated\BOModel\DevExpress.ExpressApp.AI.SmartPastePrompt\OwnMembers\Prompt\Caption" = "Prompt"
    "Views\SmartPastePrompt_DetailView\Caption"                                                = "Prompt inteligentnego wklejania"
    "Views\SmartPastePrompt_DetailView\CaptionColon"                                           = ":"
    "Views\SmartPastePrompt_DetailView\Items\Prompt\Caption"                                   = "Prompt"
    "Views\SmartPastePrompt_ListView\Caption"                                                  = "Prompt inteligentnego wklejania"
    "Views\SmartPastePrompt_ListView\Columns\Prompt\Caption"                                   = "Prompt"
    "Views\SmartPastePrompt_LookupListView\Caption"                                            = "Prompt inteligentnego wklejania"
    "Views\SmartPastePrompt_LookupListView\Columns\Prompt\Caption"                             = "Prompt"
    "Non-calculated\ActionDesign\Actions\SmartPaste\Caption"                                   = "Inteligentne wklejanie"
})

# ── DevExpress.ExpressApp.ReportsV2 ───────────────────────────────────────────
Patch-Resx "$SrcRoot\DevExpress.ExpressApp.ReportsV2\ModuleLocalizationResources.pl.resx" -Label "ExpressApp.ReportsV2" ([ordered]@{
    "Non-calculated\Localization\Enums\DevExpress.ExpressApp.ReportsV2.ReportType\Standard\Value" = "Standardowy"
    "Views\NewReportWizardParameters_DetailView\CaptionColon"                                  = ":"
    "Views\NewReportWizardParameters_ListView\Caption"                                         = "Parametry kreatora nowego raportu"
    "Views\NewReportWizardParameters_LookupListView\Caption"                                   = "Parametry kreatora nowego raportu"
})

# ── DevExpress.ExpressApp.ReportsV2.Blazor ────────────────────────────────────
Patch-Resx "$SrcRoot\DevExpress.ExpressApp.ReportsV2.Blazor\ModuleLocalizationResources.pl.resx" -Label "ExpressApp.ReportsV2.Blazor" ([ordered]@{
    "Non-calculated\Localization\Messages\ReportDesignerAlreadyOpenedMessage\Value" = "Projektant raportów jest już otwarty. Zamknij go przed otwarciem nowej instancji."
})

# ── DevExpress.ExpressApp.Dashboards.Blazor ───────────────────────────────────
Patch-Resx "$SrcRoot\DevExpress.ExpressApp.Dashboards.Blazor\ModuleLocalizationResources.pl.resx" -Label "ExpressApp.Dashboards.Blazor" ([ordered]@{
    "Localization\Messages\DashboardDesignerAlreadyOpenedMessage\Value" = "Projektant dashboardu jest już otwarty. Zamknij go przed otwarciem nowej instancji."
})

# ── DevExpress.ExpressApp.Office.Blazor ───────────────────────────────────────
Patch-Resx "$SrcRoot\DevExpress.ExpressApp.Office.Blazor\ModuleLocalizationResources.pl.resx" -Label "ExpressApp.Office.Blazor" ([ordered]@{
    "Non-calculated\BOModel\DevExpress.ExpressApp.Office.Blazor.Controllers.BlazorRichTextMailMergeObject\Caption"                          = "Korespondencja seryjna RTF (Blazor)"
    "Non-calculated\BOModel\DevExpress.ExpressApp.Office.Blazor.Controllers.BlazorRichTextMailMergeObject\OwnMembers\MergedDocument\Caption" = "Scalony dokument"
    "Views\BlazorRichTextMailMergeObject_DetailView\Caption"                                   = "Korespondencja seryjna RTF (Blazor)"
    "Views\BlazorRichTextMailMergeObject_DetailView\CaptionColon"                              = ":"
    "Views\BlazorRichTextMailMergeObject_DetailView\Items\MergedDocument\Caption"              = "Scalony dokument"
    "Views\BlazorRichTextMailMergeObject_ListView\Caption"                                     = "Korespondencja seryjna RTF (Blazor)"
    "Views\BlazorRichTextMailMergeObject_ListView\Columns\MergedDocument\Caption"              = "Scalony dokument"
    "Views\BlazorRichTextMailMergeObject_LookupListView\Caption"                               = "Korespondencja seryjna RTF (Blazor)"
    "Views\BlazorRichTextMailMergeObject_LookupListView\Columns\MergedDocument\Caption"        = "Scalony dokument"
})

# ── DevExpress.ExpressApp.Persistent.Base (PropertyNamesRes) ──────────────────
Patch-Resx "$SrcRoot\DevExpress.ExpressApp.Persistent.Base\Resources\PropertyNamesRes.pl.resx" -Label "Persistent.Base.PropertyNamesRes" ([ordered]@{
    "DevExpress.Persistent.Base.ReportsV2.CollectionDataSource"                    = "Kolekcja jako źródło danych"
    "DevExpress.Persistent.Base.ReportsV2.DataSourceBase.Criteria"                 = "Kryteria"
    "DevExpress.Persistent.Base.ReportsV2.DataSourceBase.ObjectTypeName"           = "Nazwa typu obiektu"
    "DevExpress.Persistent.Base.ReportsV2.DataSourceBase.Sorting"                  = "Sortowanie"
    "DevExpress.Persistent.Base.ReportsV2.DataSourceBase.TopReturnedRecords"       = "Maksymalna liczba rekordów"
    "DevExpress.Persistent.Base.ReportsV2.ViewDataSource"                          = "Widok jako źródło danych"
    "DevExpress.Persistent.Base.ReportsV2.ViewDataSource.Properties"               = "Właściwości"
})
